#[repr(u16)]
#[derive(Copy, Clone)]  // Add these
pub enum CharType {
    CharA = 0,
    CharB = 1,
    CharC = 2,
    CharD = 3,
    CharE = 4,
    CharF = 5,
    CharG = 6,
    CharH = 7,
    CharI = 8,
    CharJ = 9,
    CharK = 10,
    CharL = 11,
    CharM = 12,
    CharN = 13,
    CharO = 14,
    CharP = 15,
    CharQ = 16,
    CharR = 17,
    CharS = 18,
    CharT = 19,
    CharU = 20,
    CharV = 21,
    CharW = 22,
    CharX = 23,
    CharY = 24,
    CharZ = 25,
    Char0 = 26,
    Char1 = 27,
    Char2 = 28,
    Char3 = 29,
    Char4 = 30,
    Char5 = 31,
    Char6 = 32,
    Char7 = 33,
    Char8 = 34,
    Char9 = 35,
    CharPeriod = 36,
    CharQuestion = 37,
    CharExclamation = 38,
    CharSemicolon = 39,
    CharColon = 40,
    CharHashtag = 41,
    CharPrecent = 42,
    CharCloseBracket = 43,
    CharOpenBracket = 44,
    CharForwardSlash = 45,
    CharMinus = 46,
}

impl CharType {
    /// Get the ID value of the enum variant
    pub fn get_id(&self) -> u16 {
        *self as u16
    }

    pub fn get_total_chars() -> u16 {
        return 47;
    }

    /// Convert a character to its corresponding BlockType enum variant
    pub fn from_char(c: char) -> Option<Self> {
        match c {
            'A' | 'a' => Some(CharType::CharA),
            'B' | 'b' => Some(CharType::CharB),
            'C' | 'c' => Some(CharType::CharC),
            'D' | 'd' => Some(CharType::CharD),
            'E' | 'e' => Some(CharType::CharE),
            'F' | 'f' => Some(CharType::CharF),
            'G' | 'g' => Some(CharType::CharG),
            'H' | 'h' => Some(CharType::CharH),
            'I' | 'i' => Some(CharType::CharI),
            'J' | 'j' => Some(CharType::CharJ),
            'K' | 'k' => Some(CharType::CharK),
            'L' | 'l' => Some(CharType::CharL),
            'M' | 'm' => Some(CharType::CharM),
            'N' | 'n' => Some(CharType::CharN),
            'O' | 'o' => Some(CharType::CharO),
            'P' | 'p' => Some(CharType::CharP),
            'Q' | 'q' => Some(CharType::CharQ),
            'R' | 'r' => Some(CharType::CharR),
            'S' | 's' => Some(CharType::CharS),
            'T' | 't' => Some(CharType::CharT),
            'U' | 'u' => Some(CharType::CharU),
            'V' | 'v' => Some(CharType::CharV),
            'W' | 'w' => Some(CharType::CharW),
            'X' | 'x' => Some(CharType::CharX),
            'Y' | 'y' => Some(CharType::CharY),
            'Z' | 'z' => Some(CharType::CharZ),
            '0' => Some(CharType::Char0),
            '1' => Some(CharType::Char1),
            '2' => Some(CharType::Char2),
            '3' => Some(CharType::Char3),
            '4' => Some(CharType::Char4),
            '5' => Some(CharType::Char5),
            '6' => Some(CharType::Char6),
            '7' => Some(CharType::Char7),
            '8' => Some(CharType::Char8),
            '9' => Some(CharType::Char9),
            '.' => Some(CharType::CharPeriod),
            '?' => Some(CharType::CharQuestion),
            '!' => Some(CharType::CharExclamation),
            ';' => Some(CharType::CharSemicolon),
            ':' => Some(CharType::CharColon),
            '#' => Some(CharType::CharHashtag),
            '%' => Some(CharType::CharPrecent),
            ']' => Some(CharType::CharCloseBracket),
            '[' => Some(CharType::CharOpenBracket),
            '/' => Some(CharType::CharForwardSlash),
            '-' => Some(CharType::CharMinus),
            _ => None,
        }
    }
}
